### PR TITLE
Harvester part two

### LINKED ISSUE #110: Ability to harvest & earn credits
_prerequisite_
- [x] After the ability to construct and place a structure, use that logic to build a Refinery (and place it). PR #117 
- [x] concept of money #122 
- [x] harvester unit #139

_harvester logic_
- [x] Harvester spawns from refinery upon placement of refinery
- [x] Harvester moves to spice field
- [x] Harvester mines spice
- [x] When harvester is full, it returns to nearest refinery
- [x] Harvester 'enters' refinery
- [x] Once harvester has entered refinery the player gains credits
- [x] When harvester is 'empty' it will leave the refinery

_new concepts this issue introduces_
- [x] ability for units to 'enter' structures and 'leave'
- [x] harvest logic for unit
- [x] return & drop spice into refinery logic
- [x] refinery animation (harvester approaching)
- [x] harvester 'in refinery' building animation, do not render unit when dumping spice

_rules.ini_
- [ ] `harvestCapacity` in `rules.ini`
- [ ] `harvestSpeed` & `harvestAmount` property in `rules.ini`

_todo's_
- [ ] fix all TODO-HARVESTER's
- [ ] unit tests
- [ ] fix #160

### LINKED ISSUE #156: Enable harvester abilities through property in INI file
Now the harvester property in the `EntityData` object is based on the name `HARVESTER` (see `EntitiesData` in method `addUnit`). This should be a property read from the INI file.

Of course, the behavior should also be consistently working with this property, no more name references.

### LINKED ISSUE #160: Harvester refuses to die immediately when harvesting and receiving lethal damage
Given a harvester that is in `HarvestingState` , when it takes damage so that it dies, it will remain in the HarvestingState before actually dying. What happens is that it will continue harvesting until the cell is harvester and *then* it will die.

### PR DESCRIPTION
**Pull request by stefanhendriks**
Fixes #110 

Todo:
- [x] when a harvester dies in a refinery, it should stop depositing money. This will probably also fix #160 

- [x] show progress bar on harvester instead of number of resources mined
- [x] when harvester enters refinery it should no longer be able to receive commands (ie become unselected)
- [x] investigate when/why/how the game crashes when 2 harvesters want to board the same refinery at the same time. Or when a refinery is already occupied and being boarded again?
- [x] figure out the map bounds (again), deferred to #178 
- [x] (unit) testing
- [x] when harvester(s) are selected, and mouse is above a refinery, and clicked, then the harvesters should head back (there is a quirk still, deferred to #180)
- [x] codacy feedback
- [x] Resolved all `TODO-HARVESTER` for #156  (fixes #156)
- [x] Resolved all `TODO-HARVESTER` remaining tasks

### CODE REVIEW

**Comment by arjenvanderende** [comment]
Very nice! I've tested it locally and it seems to work quite nicely.
I have encountered two bugs though:

  * One crash due to two harvesters entering the same refinery. The first harvester was already docked and unloading it's spice. I can't quite remember what happened, but I think I saw the first harvester in the lower right corner (instead of being centered in both rightmost cells). The second harvester then entered via the upper right corner and then the game immediately crashed.

* If you have a harvester selected while entering the refinery, it stays selected. You can still control it while it's unloading the spice. It gave me a good laugh 😉 . I've made a short video to show the effect:
  [IMAGE ALT TEXT HERE](https://youtu.be/10gYatLduak)

**Comment by arjenvanderende** [comment]
Found another issue while trying to reproduce the crash. Closely watch the harvester coming outside the upper refinery in the following video:

[Bug video](https://youtu.be/4nGnEiwuqtU)

This harvester drives outside of the map to harvest some spice and then drives back onto the map. At the end of the video I try to scroll upwards, but since I'm already there the viewport doesn't budge 😉 

Should we prevent pathfinding from finding these cells? Or should we adjust the map generation algorithm to not place spice in the single row that is outside of the visible portion of the viewport?

**Comment by stefanhendriks** [comment]
nice finds,

yeah I knew about the 'unit moves out of viewport' bug, not sure if i administrated it. There is a method that checks if a cell is out of bounds or not (ie, on the invisible border).

Even still, I don't really get these map bounds yet, they seem to work on the Y axis fine, but we also saw crashes on the X axis I believe.

**Comment by stefanhendriks** [comment]
Updated description with comments from @arjenvanderende in todo list

**Pull request merged**
